apiVersion: v1
kind: Service
{{ template "common.metadata" . }}
spec:
  type: {{ .Values.ServiceType }}
  ports:
  - name: http
    port: {{ .Values.ServicePort }}
    targetPort: http
  selector:
    app: {{ template "common.name" . }}
    release: {{ .Release.Name | quote }}